#!/usr/bin/env bash
#Install nginx on your web-01
sudo apt-get update -y
sudo apt-get install -y nginx
sudo chown -R "$USER":"$USER" /var/www/
echo "Hello World!" > /var/www/html/index.nginx-debian.html
l="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "26i $l" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
