#!/usr/bin/env bash
#redirection
sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debaian.html
replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"
sudo sed -i "s/server_name _;/$replace/" /etc/nginx/sites-enabled/default

sudo service nginx restart
