#!/usr/bin/env bash
# Configure HAProxy to send traffic to web-01 and web-02 servers

#step 1- instal
sudo apt-get -y update
sudo apt-get -y install haproxy

#step 2- config @ /etc/haproxy/haproxy.cfg
replace=\
"
frontend  lerato_frontend
        bind *:80
        mode http
        default_backend lerato_backend
backend lerato_backend
        balance roundrobin
        server 291149-web-01 100.26.247.248:80 check
        server 291149-web-02 52.91.120.195:80 check
"
echo "$replace" |" sudo tee -a /etc/haproxy/haproxy.cfg

#step 3- enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

#step 4- test config file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

#step 5- restart
sudo service haproxy restart
