#!/usr/bin/env bash
# Name of the private key
private_key_name="school"

# Number of bits for the key
key_bits="4096"

# Passphrase to protect the key
passphrase="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b $key_bits -f ~/.ssh/$private_key_name -N "$passphrase"
